export const DOCTORS_PRICING = [
  {
    title: 'ALWAYS FREE',
    currency: 'PHP',
    monthlyPrice: 0,
    users: 1,
    inclusions: [
      'Unlimited Patients',
      '3 clinics',
      '200 MB Storage',
      'Core Features',
    ],
    btnText: 'Get Started Free',
    btnRoute: 'signup-health-facilities',
  },
  {
    title: 'PREMIUM',
    currency: 'PHP',
    monthlyPrice: 488,
    annualMonthlyPrice: 399,
    users: 'per',
    inclusions: [
      'Unlimited Patients',
      'Unlimited clinics',
      '10 GB Storage',
      'Core Features',
      'Premium Features',
      'Add Ons',
    ],
    btnText: 'Get Started Free',
    btnRoute: 'signup-health-facilities',
  },
];

export const ENTERPRISE_PRICING = [
  {
    title: 'ESSENTIALS',
    currency: 'PHP',
    monthlyPrice: 0,
    users: 1,
    inclusions: [
      'Unlimited Patients',
      '3 clinics',
      '200 MB Storage',
      'Core Features',
    ],
    btnText: 'Start Free',
    btnRoute: 'signup-health-facilities',
  },
  {
    title: 'PREMIUM',
    currency: 'PHP',
    monthlyPrice: 488,
    annualMonthlyPrice: 399,
    users: 'per',
    inclusions: [
      'Unlimited Patients',
      'Unlimited clinics',
      '10 GB Storage',
      'Core Features',
      'Premium Features',
      'Add Ons',
      'Chat Support',
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    title: 'PLATINUM',
    currency: 'PHP',
    monthlyPrice: 788,
    annualMonthlyPrice: 699,
    users: 'per',
    inclusions: [
      'Unlimited Patients',
      'Unlimited clinics',
      '10 GB Storage',
      'Core Features',
      'Premium Features',
      'Add Ons',
      'Chat Support',
      'Call & Email Support',
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    title: 'ENTERPRISE',
    requireContact: true,
    inclusions: [
      'Customizable Features',
      'Flexible Storage',
      'Dedicated Support',
      'Dedicated Project Timeline',
    ],
    btnText: 'Contact Us',
  },
];
