export const DOCTORS_PRICING = [
  {
    facilityType: 'doctor',
    value: 'lite',
    title: 'Lite',
    description: 'All the essential tools for physicians doing solo practice',
    image: 'Essentials',
    currency: '₱',
    monthlyPrice: 0,
    annualPrice: 0,
    users: 1,
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: '200 MB Storage', valid: true },
      { text: '₱ 75 Fee per Teleconsult', valid: true },
      { text: 'Professional Website', valid: true },
      { text: 'Multiple Devices', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: false },
      { text: 'Cross-clinic search', valid: false },
      { text: 'Add On Purchases', valid: false },
    ],
    btnText: 'Start Free',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'doctor',
    value: 'premium',
    title: 'Premium',
    description: 'Build modern clinics with your secretary or colleagues',
    image: 'Premium',
    currency: '₱',
    monthlyPrice: 488,
    annualPrice: 399,
    users: 'per',
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: '10 GB Storage', valid: true },
      { text: '₱ 50 Fee per Teleconsult', valid: true },
      { text: 'Professional Website', valid: true },
      { text: 'Multiple Devices', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: true },
      { text: 'Cross-clinic search', valid: true },
      { text: 'Add On Purchases', valid: true },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
];

export const CLINICS_PRICING = [
  {
    facilityType: 'clinic',
    value: 'lite',
    title: 'Lite',
    description: 'Essential features for growing outpatient clinics',
    image: 'Essentials',
    currency: '₱',
    monthlyPrice: 4999,
    annualPrice: 4488,
    // users: 1,
    inclusions: [
      { text: 'Up to 10 users', valid: true },
      { text: '5 GB Storage', valid: true },
      { text: '₱ 75 Fee per Teleconsult', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Work Offline', valid: false },
      { text: 'Materials Management', valid: false },
      { text: 'Laboratory', valid: false },
      { text: 'Imaging', valid: false },
      { text: 'Physical Medical Exam', valid: false },
      { text: 'Pharmacy', valid: false },
      { text: 'Dental', valid: false },
      { text: 'PRM', valid: false },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'clinic',
    value: 'premium',
    title: 'Premium',
    description: 'Advanced tools for medium-sized outpatient clinics',
    image: 'Premium',
    currency: '₱',
    monthlyPrice: 9999,
    // annualPrice: 399,
    // users: 'per',
    inclusions: [
      { text: 'Up to 20 users', valid: true },
      { text: '10 GB Storage', valid: true },
      { text: '₱ 60 Fee per Teleconsult', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Work Offline', valid: true },
      { text: 'Materials Management', valid: true },
      { text: 'Laboratory', valid: true },
      { text: 'Imaging', valid: true },
      { text: 'Physical Medical Exam', valid: false },
      { text: 'Pharmacy', valid: false },
      { text: 'Dental', valid: false },
      { text: 'PRM', valid: false },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'clinic',
    value: 'platinum',
    title: 'Platinum',
    description: 'Full CMS experience for advanced outpatient clinic services',
    image: 'Platinum',
    currency: '₱',
    monthlyPrice: 14999,
    // annualPrice: 699,
    // users: 'per',
    inclusions: [
      { text: 'Up to 30 users', valid: true },
      { text: '50 GB Storage', valid: true },
      { text: '₱ 50 Fee per Teleconsult', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Work Offline', valid: true },
      { text: 'Materials Management', valid: true },
      { text: 'Laboratory', valid: true },
      { text: 'Imaging', valid: true },
      { text: 'Physical Medical Exam', valid: true },
      { text: 'Pharmacy', valid: true },
      { text: 'Dental', valid: true },
      { text: 'PRM', valid: true },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'clinic',
    value: 'enterprise',
    title: 'Enterprise',
    description: 'Perfect for multi-branch healthcare facilities doing large-scale operations',
    image: 'Enterprise',
    requireContact: true,
    inclusions: [
      { text: 'Unlimited Users', valid: true },
      { text: 'Flexible Storage', valid: true },
      { text: 'Dedicated Support', valid: true },
      { text: 'Dedicated Project Timeline', valid: true },
      { text: 'White-labeled Patient Portal', valid: true },
      { text: 'API Integration', valid: true },
      { text: 'Multi-branch Functions', valid: true },
      { text: 'Customizable Features', valid: true },
    ],
    btnText: 'Contact Us',
  },
];

export const DIAGNOSTICS_PRICING = [
  {
    facilityType: 'diagnostic',
    value: 'lite',
    title: 'Lite',
    description: 'Essential features for growing diagnostic centers',
    image: 'Essentials',
    currency: '₱',
    monthlyPrice: 2499,
    // annualPrice: 0,
    // users: 1,
    inclusions: [
      { text: 'Up to 5 users', valid: true },
      { text: '3 GB Storage', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Materials Management', valid: false },
      { text: 'Laboratory', valid: false },
      { text: 'Imaging', valid: false },
      { text: 'Physical Medical Exam', valid: false },
      { text: 'PRM', valid: false },
      { text: 'Work Offline', valid: false },
      { text: 'Mobile Labs', valid: false },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'diagnostic',
    value: 'premium',
    title: 'Premium',
    description: 'Advanced tools for medium-sized diagnostic centers',
    image: 'Premium',
    currency: '₱',
    monthlyPrice: 4999,
    // annualPrice: 399,
    // users: 'per',
    inclusions: [
      { text: 'Up to 10 users', valid: true },
      { text: '5 GB Storage', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Materials Management', valid: true },
      { text: 'Laboratory', valid: true },
      { text: 'Imaging', valid: true },
      { text: 'Physical Medical Exam', valid: false },
      { text: 'PRM', valid: false },
      { text: 'Work Offline', valid: false },
      { text: 'Mobile Labs', valid: false },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'diagnostic',
    value: 'diagnostics-platinum',
    title: 'Platinum',
    description: 'Full diagnostic tools for advanced and high-volume diagnostic centers',
    image: 'Platinum',
    currency: '₱',
    monthlyPrice: 9999,
    // annualPrice: 699,
    // users: 'per',
    inclusions: [
      { text: 'Up to 20 users', valid: true },
      { text: '10 GB Storage', valid: true },
      { text: 'Patient Portal Online Results', valid: true },
      { text: 'Classic Booking Website', valid: true },
      { text: 'Full Core Features', valid: true },
      { text: 'Materials Management', valid: true },
      { text: 'Laboratory', valid: true },
      { text: 'Imaging', valid: true },
      { text: 'Physical Medical Exam', valid: true },
      { text: 'PRM', valid: true },
      { text: 'Work Offline', valid: true },
      { text: 'Mobile Labs', valid: true },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
  },
  {
    facilityType: 'diagnostic',
    value: 'enterprise',
    title: 'Enterprise',
    description: 'Perfect for multi-branch healthcare facilities doing large-scale operations',
    image: 'Enterprise',
    requireContact: true,
    inclusions: [
      { text: 'Unlimited Users', valid: true },
      { text: 'Flexible Storage', valid: true },
      { text: 'Dedicated Support', valid: true },
      { text: 'Dedicated Project Timeline', valid: true },
      { text: 'White-labeled Patient Portal', valid: true },
      { text: 'API Integration', valid: true },
      { text: 'Multi-branch Functions', valid: true },
      { text: 'Customizable Features', valid: true },
    ],
    btnText: 'Contact Us',
  },
];

export const ALL_PRICING = [
  ...DOCTORS_PRICING,
  ...CLINICS_PRICING,
  ...DIAGNOSTICS_PRICING,
];
