export const DOCTORS_PRICING = [
  {
    title: 'ALWAYS FREE',
    image: 'Essentials',
    currency: 'PHP',
    monthlyPrice: 0,
    annualMonthlyPrice: 0,
    users: 1,
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: '3 clinics', valid: true },
      { text: '200 MB Storage', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: false },
      { text: 'Add Ons', valid: false },
    ],
    btnText: 'Get Started Free',
    btnRoute: 'signup-health-facilities',
  },
  {
    title: 'PREMIUM',
    image: 'Premium',
    currency: 'PHP',
    monthlyPrice: 488,
    annualMonthlyPrice: 399,
    users: 'per',
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: 'Unlimited clinics', valid: true },
      { text: '10 GB Storage', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: true },
      { text: 'Add Ons', valid: true },
    ],
    btnText: 'Get Started Free',
    btnRoute: 'signup-health-facilities',
  },
];

export const ENTERPRISE_PRICING = [
  {
    title: 'ESSENTIALS',
    image: 'Essentials',
    currency: 'PHP',
    monthlyPrice: 0,
    annualMonthlyPrice: 0,
    users: 1,
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: '3 clinics', valid: true },
      { text: '200 MB Storage', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: false },
      { text: 'Add Ons', valid: false },
      { text: 'Chat Support', valid: false },
      { text: 'Call & Email Support', valid: false },
    ],
    btnText: 'Start Free',
    btnRoute: 'signup-health-facilities',
    value: 'essentials',
  },
  {
    title: 'PREMIUM',
    image: 'Premium',
    currency: 'PHP',
    monthlyPrice: 488,
    annualMonthlyPrice: 399,
    users: 'per',
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: 'Unlimited Clinics', valid: true },
      { text: '10 GB Storage', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: true },
      { text: 'Add Ons', valid: true },
      { text: 'Chat Support', valid: true },
      { text: 'Call & Email Support', valid: false },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
    value: 'premium',
  },
  {
    title: 'PLATINUM',
    image: 'Platinum',
    currency: 'PHP',
    monthlyPrice: 788,
    annualMonthlyPrice: 699,
    users: 'per',
    inclusions: [
      { text: 'Unlimited Patients', valid: true },
      { text: 'Unlimited Clinics', valid: true },
      { text: '100 GB Storage', valid: true },
      { text: 'Core Features', valid: true },
      { text: 'Premium Features', valid: true },
      { text: 'Add Ons', valid: true },
      { text: 'Chat Support', valid: true },
      { text: 'Call & Email Support', valid: true },
    ],
    btnText: 'Get Started',
    btnRoute: 'signup-health-facilities',
    value: 'platinum',
  },
  {
    title: 'ENTERPRISE',
    image: 'Enterprise',
    requireContact: true,
    inclusions: [
      { text: 'Customizable Features', valid: true },
      { text: 'Flexible Storage', valid: true },
      { text: 'Dedicated Support', valid: true },
      { text: 'Dedicated Project Timeline', valid: true },
    ],
    btnText: 'Contact Us',
  },
];
