mage: node:8.9.3

pipelines:
  branches:
    prod:
      - step:
          name: Deploy to Firebase
          caches:
            - node
          script:
          - npm install
          - npm run build
          - npm run deploy:fb:hosting:ci