# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install node@v8.12.0
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            sudo apt-get install -y nodejs

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build!
      - run:
          name: Build WebApp
          command: npm run build
      
      # install firebase!
      - run:
          name: Install Firebase CLI
          command: npm run install firebase-tools --save-dev
      
      # run deploy!
      - run:
          name: Deploy to Firebase
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  publish:
    jobs: 
      - deploy:
          filters:
            branches: 
              only: master
