# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install node@v10.16.0
          command: |
            curl https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
            source ~/.profile
            nvm --version
            nvm install v10.16.0
            nvm use v10.16.0
      - run:
          name: Install Yarn
          command: |
            npm install yarn -g

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      # run build!
      - run:
          name: Build WebApp
          command: yarn build
      
      # install firebase!
      - run:
          name: Install Firebase CLI
          command: yarn add firebase-tools -D
      
      # run deploy!
      - run:
          name: Deploy to Firebase
          command: yarn deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  publish:
    jobs: 
      - deploy:
          filters:
            branches: 
              only: master
