name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn
        run: npm install yarn@latest -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        env: 
          VUE_APP_API: ${{ secrets.VUE_APP_API }}
          VUE_APP_CMS_URL: ${{ secrets.VUE_APP_CMS_URL }}
          VUE_APP_ENV: ${{ secrets.VUE_APP_ENV }}
          VUE_APP_SIGNIN_URL: ${{ secrets.VUE_APP_SIGNIN_URL }}
        run: yarn build
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn deploy:prod
