name: Deploy

on: 
  pull_request:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn
        run: npm install yarn@latest -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn deploy:prod
