name: Deploy

on: 
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/setup-node@v1
      - name: Install yarn
        run: npm install yarn -g
  build:
    name: Build web app
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/setup-node@v1
      - name: Run build
        run: yarn build
  deploy:
    name: Deploy to hosting
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/setup-node@v1
      - name: Run deploy
      - env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn deploy:prod
