name: Deploy:Prod

on: 
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy PROD hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Yarn
        run: npm install yarn@latest -g
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        env: 
          API_URL: ${{ secrets.PROD_API_URL }}
          CMS_URL: ${{ secrets.PROD_CMS_URL }}
          ENV: ${{ secrets.PROD_ENV }}
          GA_ID: ${{ secrets.PROD_GA_ID }}
          IPSTACK_API_KEY: ${{ secrets.PROD_IPSTACK_API_KEY }}
          IPSTACK_API: ${{ secrets.PROD_IPSTACK_API }}
          PX_PORTAL_URL: ${{ secrets.PROD_PX_PORTAL_URL }}
          SIGNIN_URL: ${{ secrets.PROD_SIGNIN_URL }}
          STRIPE_CHECKOUT_CANCEL_URL: ${{ secrets.PROD_STRIPE_CHECKOUT_CANCEL_URL }}
          STRIPE_CHECKOUT_SUCCESS_URL: ${{ secrets.PROD_STRIPE_CHECKOUT_SUCCESS_URL }}
          STRIPE_PK: ${{ secrets.PROD_STRIPE_PK }}
        run: yarn generate
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use mycure-ab311
          firebase target:clear hosting prod
          firebase target:apply hosting prod mycure-ab311
          yarn deploy:prod