name: Run ESLint

on: 
  pull_request:
    branches: [master, environment/staging]

jobs:
  deploy_to_live:
    name: Deploy staging hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Yarn
        run: npm install yarn@latest -g
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run Build
        run: yarn build
