name: Deploy:Staging

on: 
  push:
    branches:
      - environment/staging

jobs:
  deploy_to_live:
    name: Deploy staging hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # - name: Install Yarn
      #   run: npm install yarn@latest -g
      # - name: Install Firebase Tools
      #   run: npm install firebase-tools -g
      # - name: Install dependencies
      #   run: yarn
        run: echo foo
      - name: Run build
        env: 
          VUE_APP_API: ${{ secrets.VUE_APP_STAGING_API }}
          VUE_APP_CMS_URL: ${{ secrets.VUE_APP_STAGING_CMS_URL }}
          VUE_APP_ENV: ${{ secrets.VUE_APP_STAGING_ENV }}
          VUE_APP_IPSTACK_API: ${{ secrets.VUE_APP_STAGING_IPSTACK_API }}
          VUE_APP_IPSTACK_API_KEY: ${{ secrets.VUE_APP_STAGING_IPSTACK_API_KEY }}
          VUE_APP_STRIPE_PK: ${{ secrets.VUE_APP_STAGING_STRIPE_PK }}
          GA_ID: ${{ secrets.GA_STAGING_ID }}
        # run: yarn generate
        run: |
          echo 1
          echo VUE_APP_API $VUE_APP_STAGING_API
          echo FIREBASE_TOKEN $FIREBASE_TOKEN
          echo GA_ID $GA_ID
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo 2
          echo VUE_APP_API $VUE_APP_STAGING_API
          echo FIREBASE_TOKEN $FIREBASE_TOKEN
          echo GA_ID $GA_ID
          # firebase use mc-v4-stg
          # firebase target:clear hosting staging
          # firebase target:apply hosting staging staging-web-main
          # yarn deploy:stg
