name: Deploy:Staging

on: 
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy staging hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Yarn
        run: npm install yarn@latest -g
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        env: 
          VUE_APP_API: ${{ secrets.VUE_APP_STAGING_API }}
          VUE_APP_CMS_URL: ${{ secrets.VUE_APP_STAGING_CMS_URL }}
          VUE_APP_ENV: ${{ secrets.VUE_APP_STAGING_ENV }}
          VUE_APP_IPSTACK_API: ${{ secrets.VUE_APP_STAGING_IPSTACK_API }}
          VUE_APP_IPSTACK_API_KEY: ${{ secrets.VUE_APP_STAGING_IPSTACK_API_KEY }}
        run: yarn build
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting:staging-web-main -P ${{ secrets.FIREBASE_STAGING_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
